#!/bin/bash

for i in longchain_separated 
do
	make -C ./$i clean-check > /dev/null 
	make  -C ./$i input.stitchedup.bc  > /dev/null
	make -C ./$i input.stitchedup.v > /dev/null
	cmp -s ./$i/input.stitchedup.bc ./$i/golden.bc
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then 
	    echo  "$i ... PASS" 
	else 
	    echo  "$i ... FAIL" 
	fi
done
