##===-- lib/Target/Verilog/Makefile ---------------------------------------===//
##
## This file is distributed under the LegUp license. See LICENSE for details.
##
##===----------------------------------------------------------------------===//

LEVEL = ../../..
LIBRARYNAME = LLVMStitchUpCodeGen
TARGET = StitchUp 
BUILD_ARCHIVE = 1

DIRS = TargetInfo

include $(LEVEL)/Makefile.common

CompileCommonOpts += -Wno-format
