LEVEL = ../../..
include ../../Makefile.common

clean:
	rm -f tmp.bc *.rpt *.dot *.orig.bc *.stitchedup.bc *.orig.v *.stitchedup.v *.qsf *.tex *.sdc *.txt *.mif *.orig_c.v *.stitchedup_c.v *.keep *runVsim *_tb.v *.wrapper.v transcript     
	rm -f -r work
