LEVEL=../../..
include ../../Makefile.common

check: input.stitchedup.ll
	./check
	
clean-check:
	rm -r -f input.stitchedup.bc input.stitchedup.ll test.log *.tex *.dot *.rpt *.mif *.txt *.qsf *.sdc tmp.bc *.v	
