#!/bin/bash

for i in conditional_branch conditional_branch_withdata  loadandstore loadandstore_withdata  straightline  unconditional_branch longchain_separated longchain_touching phi array 
do
	make -C ./$i clean-check > /dev/null 
	make  -C ./$i input.stitchedup.bc  > /dev/null
	cmp -s ./$i/input.stitchedup.bc ./$i/golden.bc
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then 
	    echo  "$i ... PASS" 
	else 
	    echo  "$i ... FAIL" 
	fi
done
